language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
install: "pip install -r requirements.txt"
cache: pip
env:
  - APPNAME_ENV=test
# command to run tests
script: ./manage.py test --coverage
