# In case you want to use Travis: move this file to the top level folder
language: python
python:
  - "3.7"
  - "3.8"
 
# command to install dependencies
install: "pip install -r requirements.txt"
cache: pip
env:
  - APPNAME_ENV=test
# command to run tests
script: ./manage.py test --coverage
